config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  get 'user/index'

  get 'home/index'

  resources :products
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
    get '/product_new' => 'products#new_map'
    post '/product_map' => 'products#create_map'
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image_address, ImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user! 
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def new_map
  end
  def create_map
        u1 = Product.new
        u1.latitude =  session[:map_lat]
        u1.longitude = session[:map_lng]
        u1.area_name = params[:area_name]
        u1.address = params[:address]
        u1.save
        redirect_to "/"
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:area_type,:area_name,:address,:latitude,:longitude,:description,:image_address)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="py-4 text-center">
  <fieldset disabled>
  <div class = "from-group mx-auto" style="width:200px">
    <%=f.label :latitude%><br/>
    <%=f.text_field :latitude, id: 'lat' ,class: "form-control"%>
  </div>
  <div class = "from-group mx-auto" style="width:200px">
    <%=f.label :longitude%><br/>
    <%=f.text_field :longitude, id: 'lng' ,class: "form-control"%>
  </div>
  </fieldset>
  <div class = "from-group col-md-6 mx-auto">
    <%=f.label :area_type%><br/>
    <%= f.select :area_type, options_for_select([["흡연구역", "흡연구역"],["단속구역", "단속구역"]]), :class => 'genForm_dropBox' %>
  </div>
  <div class = "from-group col-md-6 mx-auto">
    <%=f.label :area_name%><br/>
    <%=f.text_field :area_name,class: "form-control"%>
  </div>
  <div class = "from-group col-md-6 mx-auto">
    <%=f.label :address%><br/>
    <%=f.text_field :address,class: "form-control"%>
  </div>
  <div class = "from-group col-md-6 mx-auto">
    <%=f.label :description%><br/>
    <%=f.text_field :description,class: "form-control"%>
  </div>
  <div class = "from-group col-md-3 mx-auto">
    <%=f.label :image_address%><br/>
    <%=f.file_field :image_address,class: "form-control"%>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "등록하기",class: 'btn btn-primary'%>
  </div>
</div>
<% end %>

app/views/products/_map.html.erb
<br/>
<form>
 &nbsp;&nbsp;&nbsp;주소 검색 : <input type="text" id="add_search" name="address" >
 <input type="button" id="search" value="검색하기">
</form>
<div class ="m-3"><div id="map" style="width:100%;height:300px;z-index: 0;"></div></div>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=&libraries=services"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new daum.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

var map = new daum.maps.Map(mapContainer, mapOption); // 지도를 생성합니다


// 지도를 클릭한 위치에 표출할 마커입니다
var marker = new daum.maps.Marker(); 
// 지도에 마커를 표시합니다
marker.setMap(map);
// 지도에 클릭 이벤트를 등록합니다
// 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다
daum.maps.event.addListener(map, 'click', function(mouseEvent) {        
    // 클릭한 위도, 경도 정보를 가져옵니다 
    var latlng = mouseEvent.latLng; 
    // 마커 위치를 클릭한 위치로 옮깁니다
    marker.setPosition(latlng);
    var lat = latlng.getLat();
    var lng = latlng.getLng();
    
    var resultlat = document.getElementById('lat'); 
     resultlat.value = lat;
    var resultlng = document.getElementById('lng'); 
     resultlng.value = lng;
});

</script>
<script>

$('#search').on('click',function(){
    var address = $('#add_search').val();
    console.log(address);
    search(address);
})
function search(address){
var geocoder = new daum.maps.services.Geocoder();

// 주소로 좌표를 검색합니다
geocoder.addressSearch(address, function(result, status) {

    // 정상적으로 검색이 완료됐으면 
     if (status === daum.maps.services.Status.OK) {

        var coords = new daum.maps.LatLng(result[0].y, result[0].x);
        var lat = coords.getLat();
        var lng = coords.getLng();
        var resultlat = document.getElementById('lat'); 
        resultlat.value = lat;
        var resultlng = document.getElementById('lng'); 
        resultlng.value = lng;
        
        // 결과값으로 받은 위치를 마커로 표시합니다
        marker.setPosition(coords);
        // 인포윈도우로 장소에 대한 설명을 표시합니다
        var infowindow = new daum.maps.InfoWindow({
            content: '<div style="width:150px;text-align:center;padding:6px 0;">정확한 위치를 집어주세요~!!</div>'
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
        
        daum.maps.event.addListener(map, 'click', function(mouseEvent) {     
        infowindow.close();
    });
    } 
});  
}
</script>
<script>

// HTML5의 geolocation으로 사용할 수 있는지 확인합니다 
if (navigator.geolocation) {
    
    // GeoLocation을 이용해서 접속 위치를 얻어옵니다
    navigator.geolocation.getCurrentPosition(function(position) {
        
        var lat = position.coords.latitude; // 위도
        
        var lng = position.coords.longitude; // 경도
        
        var resultlat = document.getElementById('lat'); 
         resultlat.value = lat;
        var resultlng = document.getElementById('lng'); 
         resultlng.value = lng;
     
        var locPosition = new daum.maps.LatLng(lat, lng), // 마커가 표시될 위치를 geolocation으로 얻어온 좌표로 생성합니다
            message = '<div style="padding:5px;">여기에 계신가요?!</div>'; // 인포윈도우에 표시될 내용입니다
        
        // 마커와 인포윈도우를 표시합니다
        displayMarker(locPosition, message);
            
      });
    
} else { // HTML5의 GeoLocation을 사용할 수 없을때 마커 표시 위치와 인포윈도우 내용을 설정합니다
    
    var locPosition = new daum.maps.LatLng(33.450701, 126.570667),    
        message = 'geolocation을 사용할수 없어요..'
        
    displayMarker(locPosition, message);
}

// 지도에 마커와 인포윈도우를 표시하는 함수입니다
function displayMarker(locPosition, message) {

    // 마커를 생성합니다
    var marker = new daum.maps.Marker({  
        map: map, 
        position: locPosition,
    }); 
    
    var iwContent = message, // 인포윈도우에 표시할 내용
        iwRemoveable = true;

    // 인포윈도우를 생성합니다
    var infowindow = new daum.maps.InfoWindow({
        content : iwContent,
        removable : iwRemoveable
    });
    
    // 인포윈도우를 마커위에 표시합니다 
    infowindow.open(map, marker);
    
    // 지도 중심좌표를 접속위치로 변경합니다
    map.setCenter(locPosition); 
    daum.maps.event.addListener(map, 'click', function(mouseEvent) {     
        marker.setVisible(false);
        infowindow.close();
    });
    $('#search').on('click',function(){
        marker.setVisible(false);
        infowindow.close();
    });
}    
</script>

app/views/products/_search.html.erb
<script>

</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록하기</h1>
        </div>
        <div class="right">
          <h1>dashboard /</h1>
          <a href="#">page name</a>
        </div>
      </div>
      <!-- end head bottom -->
<div class ="container">
<div id = "title" class = "row">
<%@products.each do |product|%>
<div class="card col-md-3">
  <img class="card-img-top" src="<%= product.image_address.thumb.url%>">
  <div class="card-body text-center">
    <h5 class="card-title" data_id=1><span><%=product.area_type%></span></h5>
    <p class="card-text">장소:<%=product.area_name%></p><br/>
    위도<p class="card-text"><%=product.latitude%></p><br/>
    경도<p class="card-text"><%=product.longitude%></p><br/>
    내용<p class="card-text"><%=product.address%></p>
    <%= link_to '정보보기', product_path(product), class: "btn btn-primary"%>
  </div>
</div>
<%end%>
</div>
</div>
<%= link_to 'New Product', new_product_path %>
<% content_for 'javascript_content' do %>
<%= javascript_include_tag params[:controller] %>
<% end %>

<script>
    console.log("content_for");
</script>    

app/views/products/new.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록하기</h1>
        </div>
        <div class="right">
          <h1>dashboard /</h1>
          <a href="#">page name</a>
        </div>
      </div>
<%= render 'map', product: @product %>
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: ""%>

  
<% content_for 'javascript_content' do%>
<%= javascript_include_tag params[:controller] %>
<%end%>

app/views/products/new_map.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>등록하기</h1>
        </div>
        <div class="right">
          <h1>dashboard /</h1>
          <a href="#">page name</a>
        </div>
      </div>

(:area_type,:area_name,:address,:latitude,:longitude,:description,:image_address  
  
  
<%= render 'map', product: @product %>

<form action = "/product_map" method = "POST">
    <input type = "hidden" name = "authenticity_token" value ="<%= form_authenticity_token%>">
    <input type = "text" name ="area_name" placeholder = "제목">
    <input type = "text" name ="address" placeholder = "주소">
    <input type = "text" name ="description" placeholder = "내용">
    <input type = "submit" value = "등록하기">
</form>


<%= link_to 'Back', products_path, class: ""%>

  
<% content_for 'javascript_content' do%>
<%= javascript_include_tag params[:controller] %>
<%end%>

app/views/products/show.html.erb
  <div class="content">
  <h1><%= @product.area_type %></h1>
  <hr>
  <p><%= @product.description %></p>
  <p><%=@product.area_name %></p>

<%= link_to '삭제', product_path, method: "DELETE" %> |
<%= link_to '수정', edit_product_path(@product) %> |
<%= link_to '리스트', products_path %>
  </div>
  
  <% content_for 'javascript_content' do%>
  <%= javascript_include_tag params[:controller] %>
  <%end%>